/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffe08f",
        "on-primary-fixed": "#001c38",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        "primary": "#002444",
        "tertiary-fixed": "#66ff8e",
        "on-tertiary-fixed-variant": "#005322",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#fed977",
        "on-surface-variant": "#43474e",
        "on-secondary-container": "#785d00",
        "on-primary-fixed-variant": "#2b486b",
        "surface-tint": "#436084",
        "inverse-on-surface": "#eff1f3",
        "background": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#00431a",
        "on-secondary-fixed-variant": "#584400",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#00bb56",
        "primary-fixed": "#d2e4ff",
        "tertiary": "#002b0e",
        "surface-container": "#eceef0",
        "surface": "#f8f9fb",
        "secondary": "#755b00",
        "primary-container": "#1b3a5c",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#3de273",
        "outline": "#73777f",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fb",
        "on-tertiary-fixed": "#002109",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#abc9f2",
        "surface-dim": "#d8dadc",
        "outline-variant": "#c3c6cf",
        "on-secondary-fixed": "#241a00",
        "secondary-fixed-dim": "#e6c364",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#87a4cc",
        "inverse-primary": "#abc9f2"
      },
      fontFamily: {
        "headline": ["Almarai", "Manrope"],
        "body": ["Tajawal", "Inter"],
        "label": ["Tajawal", "Inter"],
        "almarai": ["Almarai", "sans-serif"],
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
